#!/bin/bash

DEVICE=/dev/ttyUSB0
LOCKFILE=/tmp/.usbclockset

if [ ! -f LOCKFILE ]
then
	touch $LOCKFILE

	if [ $1 == "weather" ]
	then
		temperature=`wget http://www.e1.ru/ -O - -q | grep '&deg;C' | head -n1 | sed -e 's/<[^>]\+>//g' -e 's/,/\./' -e 's/[^0-9\.-]//g'  | awk '{ i = int($1); a=length(i);print substr("   ", 1, 3-a) i "*"; }'`
#		temperature=`wget http://www.e1.ru/weather -O - -q | grep weather_temperature | head -n1 | sed -e 's/<[^>]\+>//g' -e 's/[^0-9\-]//g' -e 's/$/*/' | awk '{ a=length($1);print substr("   ", 1, 4-a) $1; }'`
		if echo -n "$temperature" | grep -E '^[ 0-9\*\.-]+$' >/dev/null
		then
			command1='{M1,'"$temperature"'}'
			command2='{D0,16}'
			command3='{D1,4}'
			command4='{T0,0}'
			command5='{T1,1}'
		fi
	fi

	if [ $1 == "time" ]
	then
		command1='{S'`date +%H%M%S`'}'
	fi

	if [ $1 == "reset" ]
	then
		command1='{R}'
	fi

	# run all assigned commands sequentially
	index=1
	while [ true ]
	do
		eval command='$'command$index
		if [ ! -z "$command" ]
		then
			# 3 attempts to run the command
			for k in 1 2 3
			do
				if usbclock $DEVICE "$command"
				then
					break
				fi
				
				# sleep a little if error
				sleep 1
			done
		fi

		exit
	done
	
	rm $LOCKFILE
fi	
