#!/bin/bash

DEVICE=/dev/usb/tts/0
LOCKFILE=/tmp/.usbclockset

if [ ! -f LOCKFILE ]
then
	touch $LOCKFILE

	if [ $1 == "weather" ]
	then
		temperature=`wget http://www.e1.ru/ -O - -q | grep '&deg;C' | head -n1 | sed -e 's/<[^>]\+>//g' -e 's/[^0-9\.-]//g'  | awk '{ i = int($1); a=length(i);print substr("   ", 1, 3-a) i "*"; }'`
#		temperature=`wget http://www.e1.ru/weather -O - -q | grep weather_temperature | head -n1 | sed -e 's/<[^>]\+>//g' -e 's/[^0-9\-]//g' -e 's/$/*/' | awk '{ a=length($1);print substr("   ", 1, 4-a) $1; }'`
		if echo -n "$temperature" | grep -E '^[ 0-9\*\.-]+$' >/dev/null
		then
			usbclock $DEVICE '{M1,'"$temperature"'}'
			usbclock $DEVICE '{D0,16}'
			usbclock $DEVICE '{D1,4}'
			usbclock $DEVICE '{T0,0}'
			usbclock $DEVICE '{T1,1}'
		fi
	fi

	if [ $1 == "time" ]
	then
		usbclock $DEVICE '{S'`date +%H%M%S`'}'
	fi

	if [ $1 == "reset" ]
	then
		usbclock $DEVICE '{R}'
	fi
	
	rm $LOCKFILE
fi	
